### ISSUE TITLE
Connection strategy not found

### ISSUE THREAD

**Issue by custertian** [processing/p5.js-web-editor#140]
p5.js-web-editor/node_modules/connect-mongo/src/index.js:105
                throw new Error('Connection strategy not found');
                ^

Error: Connection strategy not found
    at MongoStore (/home/custer/Yak/work/Git/p5.js-web-editor/node_modules/connect-mongo/src/index.js:105:23)
    at Object.<anonymous> (/home/custer/Yak/work/Git/p5.js-web-editor/server/server.js:51:10)
    at Module._compile (module.js:556:32)
    at loader (/home/custer/Yak/work/Git/p5.js-web-editor/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/custer/Yak/work/Git/p5.js-web-editor/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/custer/Yak/work/Git/p5.js-web-editor/index.js:4:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
[nodemon] app crashed - waiting for file changes before starting...

**Comment by catarak** [comment]
Did you add a `.env` file to the project? In `README.md` there's an example of what this file should look like. For development, you'll need to put real values for `MONGO_URL`, `PORT`, and `SESSION_SECRET`, but for the rest of the values you can put gibberish, unless you need to work on uploading media files or Github login.

**Comment by custertian** [comment]
thank you for your help .Yeah, i hd .env
NGO_URL=mongodb://localhost:27017/p5js-web-editor
PORT=8000
SESSION_SECRET=test
AWS_ACCESS_KEY=<test>
AWS_SECRET_KEY=<test>
S3_BUCKET=<test>
GITHUB_ID=<test>
GITHUB_SECRET=<test>

about test have write my information

**Comment by custertian** [comment]
http://localhost:27017/
It looks like you are trying to access MongoDB over HTTP on the native driver port.

**Comment by catarak** [comment]
You should be able to access the editor at http://localhost:8000, 27017 is the port that MongoDB is running on.

**Comment by catarak** [comment]
@custertian are you still having issues running the editor locally? If not, I'm going to close this ticket.
