### ISSUE TITLE
Server Error When Logging Out

### ISSUE THREAD

**Issue by raclim** [processing/p5.js-web-editor#2292]
### p5.js version

1.6.0

### What is your operating system?

Mac OS

### Web browser and version

114.0.5735.198 (Official Build) (arm64) 

### Actual Behavior

Originally found by @lindapaiste with [added details and a potential solution.](https://github.com/processing/p5.js-web-editor/pull/2271#issuecomment-1633469530). The content of this issue is based off of her comment. 

Currently there is a 500 internal server error when logging out on localhost from the `http://localhost:8000/editor/logout` API endpoint. 

### Expected Behavior

Error does not appear on logout. 

### Steps:
1. Ensure that you've logged into your account for the p5.js Web Editor. 
2. Logout by clicking on the dropdown menu on the upper-right corner, and then click on "Log Out". 
3.  (I am using Chrome DevTools) Open your browser's Developer Tools and make sure you're in the "Console" panel, which is where the error will appear.

**Comment by lindapaiste** [comment]
I'm reopening this because I am getting a 500 error when trying to log out on `localhost` and in production.

The error is suggesting that we need to use `express-session` middleware but we already are.  Something might be set up incorrectly.  I'm also wondering if #2473 might have put the actions in the wrong order, like maybe it's an error to call `req.logout` after the session has already been destroyed.  I have not investigated yet.

Triggered by this line:
https://github.com/processing/p5.js-web-editor/blob/1cf2dc3c8aa555110bab2b215544ca3abba92139/server/controllers/session.controller.js#L39

Error:
```
Error: Login sessions require session support. Did you forget to use `express-session` middleware?
    at SessionManager.logOut (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\passport\lib\sessionmanager.js:64:33)
    at IncomingMessage.logout (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\passport\lib\http\request.js:67:26)
    at C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\server\controllers\/session.controller.js:39:9
    at tryCatcher (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\bluebird\js\release\nodeify.js:23:30)
    at Promise._settlePromise (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\bluebird\js\release\promise.js:601:21)
    at Promise._settlePromise0 (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\bluebird\js\release\promise.js:673:18)
    at Promise._resolveCallback (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\bluebird\js\release\promise.js:466:57)
    at Promise._settlePromiseFromHandler (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\bluebird\js\release\promise.js:559:17)
    at Promise._settlePromise (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\bluebird\js\release\promise.js:729:18)
    at Promise._fulfill (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\bluebird\js\release\promise.js:673:18)
    at C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\bluebird\js\release\nodeback.js:42:21
    at C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\mongoose\node_modules\mongodb\lib\utils.js:390:17
    at C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\mongoose\node_modules\mongodb\lib\utils.js:378:11
    at C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\mongoose\node_modules\mongodb\lib\utils.js:704:5
    at completeEndSession (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\mongoose\node_modules\mongodb\lib\core\sessions.js:146:9)
    at C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\mongoose\node_modules\mongodb\lib\core\sessions.js:158:7
    at maybePromise (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\mongoose\node_modules\mongodb\lib\utils.js:692:3)
    at ClientSession.endSession (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\mongoose\node_modules\mongodb\lib\core\sessions.js:131:12)
    at executeCallback (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\mongoose\node_modules\mongodb\lib\utils.js:375:17)
    at handleCallback (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\mongoose\node_modules\mongodb\lib\utils.js:109:55)
    at C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\mongoose\node_modules\mongodb\lib\operations\common_functions.js:321:5
    at handler (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\mongoose\node_modules\mongodb\lib\core\sdam\topology.js:961:24)
    at C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\mongoose\node_modules\mongodb\lib\cmap\connection_pool.js:352:13
    at handleOperationResult (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\mongoose\node_modules\mongodb\lib\core\sdam\server.js:567:5)
    at MessageStream.messageHandler (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\mongoose\node_modules\mongodb\lib\cmap\connection.js:308:5)
    at MessageStream.emit (node:events:513:28)
    at MessageStream.emit (node:domain:489:12)
    at processIncomingData (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\mongoose\node_modules\mongodb\lib\cmap\message_stream.js:144:12)
    at MessageStream._write (C:\Users\Linda Paiste\PhpstormProjects\p5.js-web-editor\node_modules\mongoose\node_modules\mongodb\lib\cmap\message_stream.js:42:5)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at MessageStream.Writable.write (node:internal/streams/writable:336:10)
    at Socket.ondata (node:internal/streams/readable:754:22)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
```

**Comment by lindapaiste** [comment]
I have confirmed that #2473 is the source of the problem.
