### ISSUE TITLE
"Failed to Fetch" errors for images on web editor

### ISSUE THREAD

**Issue by angichau** [processing/p5.js-web-editor#3069]
### p5.js version

1.9.1

### What is your operating system?

Mac OS

### Web browser and version

Chrome 123.0.6312.59 

### Actual Behavior

We've been seeing this error pretty consistently during our coding classes. When students try to upload a new image, or duplicate an existing project with images, they sometimes encounter a "Failed to fetch" error with the images. It seems inconsistent which students receive this error but in a class of 18, we can usually count on about 3-4 students encountering it during a class. 

Usually, by the time the next class happens, the error has resolved itself. But it is a problem when students can't really move forward during class due to this error. 

See attached screenshots for two students' who encountered this error today:

<img width="643" alt="Screenshot 2024-03-26 at 10 42 39 AM" src="https://github.com/processing/p5.js-web-editor/assets/7041063/959bcd5c-a125-490a-baa5-11d68b73bf1f">

<img width="1258" alt="Screenshot 2024-03-26 at 10 36 41 AM" src="https://github.com/processing/p5.js-web-editor/assets/7041063/12260f74-af1d-4ebd-955f-97bf4349cf0e">

### Expected Behavior

No errors in console. And images load and display on canvas as expected. 

### Steps to reproduce

This is difficult to reproduce because it seems after a few hours, or a few days, the error resolves itself. So it doesn't seem like it's an issue with the students' code but something on the p5 server side...?

**Comment by bartzbrian** [comment]
I'm encountering an identical issue with students using images in my creative coding class. This was not an issue last semester, and the code for the students with the issue is correct according to the examples used in the p5 reference. The issue seems to be inconsistent across which students have it, and it is unclear what resolves it. Some students have fixed the error by trying different images altogether, even though the images which were not working are supported file formats and of a reasonable file size.

**Comment by rainbow-lazer** [comment]
I've also been experiencing this issue with my students recently. It is sporadic and hard to reproduce, but when I have come across it, switching browsers (from Chrome to Firefox) has seemed to help.

**Comment by rruubboott** [comment]
Same here - same issue. 
Uploaded images DO work for createImg() but not for loadImage()
It's very sporadic/inconsistent. Only effects a few (4/5 out of a class of 80).
Fixes that sometimes work: deleting / replacing image
Duplicating sketch
Or, starting brand new sketch, copying and pasting old code, re uploading images.

**Comment by steve-boyer** [comment]
Same problem. This has only popped up recently, in the past several weeks, exactly as described by other commenters above. More detailed error report:

TypeError: Failed to fetch
    at _main.default.loadImage (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.9.2/p5.js:87288:11)

    at https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.9.2/p5.js:65228:65

    at preload (blob:https://preview.p5js.org/7e7de300-2d11-4f4f-8321-f0dda00ad4eb:4:13)

    at p5._start (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.9.2/p5.js:65185:25)

    at new p5 (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.9.2/p5.js:65513:20)

    at _globalInit (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.9.2/p5.js:64409:15)

**Comment by steve-boyer** [comment]
exact problem as stated by the above commenters. Here's a detailed error report:

TypeError: Failed to fetch
    at _main.default.loadImage (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.9.2/p5.js:87288:11)

    at https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.9.2/p5.js:65228:65

    at preload (blob:https://preview.p5js.org/bf3d7c46-6f0f-42f9-a2a6-3f4c16a48474:4:13)

    at p5._start (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.9.2/p5.js:65185:25)

    at new p5 (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.9.2/p5.js:65513:20)

    at _globalInit (https://cdnjs.cloudflare.com/ajax/libs/p5.js/1.9.2/p5.js:64409:15)

**Comment by raclim** [comment]
Thank you for reporting these! We'll prioritize working on this issue and hopefully provide an update to this within the next week or so!

**Comment by PiyushChandra17** [comment]
@raclim I would like to work on this issue, can you please assign me this issue? Thanks!

**Comment by raclim** [comment]
@PiyushChandra17 assigned!

**Comment by Mcf11** [comment]
> I've also been experiencing this issue with my students recently. It is sporadic and hard to reproduce, but when I have come across it, switching browsers (from Chrome to Firefox) has seemed to help.

worked for me! Also I'd like to say that I tried to use a lot of imagens .PNG or .JPEG and the issue appeared randomly on them, by switching my browser from OperaGX to Chrome all of my images worked just fine.

**Comment by Marvellousz** [comment]
Is this issue resolved?

**Comment by marvellousz** [comment]
@raclim Is this issue resolved?

**Comment by bmoren** [comment]
Still having this issue. I would say 50% of my class was affected.

**Comment by raclim** [comment]
Thank you for the update on this! I'm sorry that it took a while to get back here—after trying a few different solutions I ended up coming to an impasse. @bmoren would you be able to share any example URLs to affected sketches?

**Comment by nreiling** [comment]
I'm having this issue (in @bmoren 's class) and somehow fixed the issue by duplicating my sketch when the problem came up. I don't know why it loaded - nothing else changed.  I was previously using createImg as a temporary fix, but this function doesn't work with tint. After changing createImg to loadImg AND duplicating the sketch, the image would work.

Here's a link to my original sketch (which wasn't working with loadImg):
https://editor.p5js.org/Nreiling/sketches/jLfg5nuOD
Here's the duplicated sketch that inexplicably worked:
https://editor.p5js.org/Nreiling/sketches/lwvfFsZLv

**Comment by msawired** [comment]
Hey @raclim, I was informed about this issue by @SableRaf. I don't have this issue at the moment on OpenProcessing, but from prior experiences with similar issues, my hunch would be on double-checking the request and response headers and MIME types. Occasionally, MIME of a file can be sent as octet-streams instead of proper jpg/png, which may cause server or client to reject the request/response. Also, any duplicate or mistyped headers can also throw off similar issues. CORS can also be generated by above (although the issue is not technically a CORS issue), because browser can not get to the CORS header due to some erroneous header before it.
Do you use any error capturing tool like Sentry? This may help you collect some relevant data to investigate further.

**Comment by raclim** [comment]
Hi @msawired, thanks so much for checking this out and thanks @SableRaf for passing this on! I did find that this was related to a CORS issue and currently implemented a temporary fix, but didn't consider it could be due to MIME types as well! I'll take a look into it and hopefully can reach a longterm solution!

**Comment by raclim** [comment]
Closing this one and directing updates on this to the linked issue right above to organize issues!
